model_name: "model_name"

# If you want to use a specific dataset path, uncomment the following line.
# Otherwise, the dataset path is `{dataset_root}/{model_name}`.

# dataset_path: "your/dataset/path"

resample:
  sampling_rate: 44100
  in_dir: "raw"
  out_dir: "wavs"

preprocess_text:
  transcription_path: "esd.list"
  cleaned_path: ""
  train_path: "train.list"
  val_path: "val.list"
  config_path: "config.json"
  val_per_lang: 4
  max_val_total: 12
  clean: true

bert_gen:
  config_path: "config.json"
  num_processes: 2
  device: "cuda"
  use_multi_device: false

style_gen:
  config_path: "config.json"
  num_processes: 4
  device: "cuda"

train_ms:
  env:
    MASTER_ADDR: "localhost"
    MASTER_PORT: 10086
    WORLD_SIZE: 1
    LOCAL_RANK: 0
    RANK: 0
  model_dir: "models"  # The directory to save the model (for training), relative to `{dataset_root}/{model_name}`.
  config_path: "config.json"
  num_workers: 16
  spec_cache: True
  keep_ckpts: 1 # Set this to 0 to keep all checkpoints

webui:  # For `webui.py`, which is not supported yet in Style-Bert-VITS2.
  # 推理设备
  device: "cuda"
  # 模型路径
  model: "models/G_8000.pth"
  # 配置文件路径
  config_path: "config.json"
  # 端口号
  port: 7860
  # 是否公开部署，对外网开放
  share: false
  # 是否开启debug模式
  debug: false
  # 语种识别库，可选langid, fastlid
  language_identification_library: "langid"

# server_fastapi's config
server:
  port: 45072
  device: "cpu"
  language: "JP"
  limit: 8192
  origins:
    - "*"
